<#
.SYNOPSIS
Install repository-local commit/push gates using an existing PRIVATE patterns file.
.DESCRIPTION
Requires Node.js, Git supporting 'hook run --to-stdin', and PowerShell (pwsh, or
Windows PowerShell). Patterns must already
exist OUTSIDE all worktrees. They are never copied into the repository. The path
is saved in local Git configuration only; existing hooks are preserved and chained.
Configuration is shared by this repository's worktrees. Run again to change the
private path. CI checks filenames only and does not receive the private patterns.
.EXAMPLE
pwsh -File scripts/setup-leak-audit.ps1 -PatternsFile "$HOME/private/folio-patterns.txt"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$PatternsFile
)

$ErrorActionPreference = 'Stop'

function Invoke-Git([string[]]$Arguments) {
    $result = & git @Arguments
    if ($LASTEXITCODE -ne 0) { throw 'A required Git operation failed; hook setup stopped.' }
    return $result
}

$repoRoot = Invoke-Git -Arguments @('rev-parse', '--show-toplevel')
$checker = Join-Path $repoRoot 'scripts/check-tracked-data.mjs'
$resolvedPatterns = (Resolve-Path -LiteralPath $PatternsFile -ErrorAction Stop).Path
& node $checker --validate-patterns $resolvedPatterns
if ($LASTEXITCODE -ne 0) { throw 'Private patterns validation failed. Nothing was installed.' }

$previousHooks = Invoke-Git -Arguments @('rev-parse', '--path-format=absolute', '--git-path', 'hooks')
$hooksDirectory = Invoke-Git -Arguments @('rev-parse', '--path-format=absolute', '--git-path', 'folio-hooks')
$templates = @{}
foreach ($hook in @('pre-commit', 'pre-push')) {
    $templates[$hook] = (@(
        '#!/bin/sh'
        '# Generated by folio; existing hooks are forwarded by the Node runner.'
        'root=$(git rev-parse --show-toplevel) || exit 1'
        ('exec node "$root/scripts/check-tracked-data.mjs" --hook ' + $hook + ' "$@"')
        ''
    ) -join "`n")
    $path = Join-Path $hooksDirectory $hook
    if ((Test-Path -LiteralPath $path) -and
        ([IO.File]::ReadAllText($path) -cne $templates[$hook])) {
        throw 'The folio hook location already contains a different hook. Nothing will be overwritten.'
    }
}

[IO.Directory]::CreateDirectory($hooksDirectory) | Out-Null
foreach ($hook in @('pre-commit', 'pre-push')) {
    $path = Join-Path $hooksDirectory $hook
    if (-not (Test-Path -LiteralPath $path)) {
        [IO.File]::WriteAllText($path, $templates[$hook], [Text.UTF8Encoding]::new($false))
    }
    if ($env:OS -ne 'Windows_NT') {
        & chmod +x -- $path
        if ($LASTEXITCODE -ne 0) { throw 'Could not mark the generated hook executable.' }
    }
}

if ([IO.Path]::GetFullPath($previousHooks) -ne [IO.Path]::GetFullPath($hooksDirectory)) {
    Invoke-Git -Arguments @('config', '--local', 'folio.previousHooksPath', $previousHooks) | Out-Null
}
Invoke-Git -Arguments @('config', '--local', 'folio.leakPatternsFile', $resolvedPatterns) | Out-Null
Invoke-Git -Arguments @('config', '--local', 'core.hooksPath', $hooksDirectory) | Out-Null
Write-Host 'Installed local pre-commit/pre-push gates; existing hooks are chained. No patterns were copied.'
